### ISSUE TITLE
Authentification with Github does not work on https://tuto.matchid.tech 

### ISSUE THREAD

**Issue by benoitguigal** [matchID-project/backend#121]
### Steps to reproduce:

- Go to https://tuto.matchid.tech 
- Click "Avec Github"
- The browser is redirected to https://tuto.matchid.tech/matchID/api/v0/authorize/github with error message 
```
{
    "message": "The server could not verify that you are authorized to access the URL requested.  You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required."
}
```

**Comment by rhanka** [comment]
Github & Facebook now should work.
The bug occured for the first login attemps before any restart of the backend.
It now should be ok, I let you test before closing.
Be clement to the authorization model, which is now not that performant (it is now desactivated by default, but is still activated on the tutorial site).

**Comment by rhanka** [comment]
Closing this as it seems now to work properly.
